#!/usr/bin/env python

import sys, os
from index import Index

def main(indexfile, terms):
  i = Index()
  f = open(indexfile)
  try:
    i.load(f)
  finally:
    f.close()

  base = i.metadata["base"]
  for x in i[terms]:
    print os.path.join(base, *x)

if __name__ == "__main__":
  if len(sys.argv) < 2:
    print "usage: %s [index file] [search term]"
  else:
    main(sys.argv[1], sys.argv[2])
