#!/usr/bin/env python

import sys, os, index

def main(indexfile, terms):
  f = open(indexfile)
  try:
    i = index.ReadIndex(f)
    try:
      base = i.metadata["base"]
      for x in i[terms]:
        print os.path.join(base, *x)
    finally:
      i.close()
  finally:
    f.close()

if __name__ == "__main__":
  if len(sys.argv) < 2:
    print "usage: %s [index file] [search term]"
  else:
    main(sys.argv[1], sys.argv[2])
