#!/usr/bin/env python

import sys, os, index

def main(indexfile, basepath):
  i = WriteIndex()

  basepath = os.path.realpath(basepath)

  i.metadata["base"] = basepath
  l = len(basepath) + 1

  for root, dirs, files in os.walk(basepath):
    xroot = root[l:]
    for x in files:
      i.add(os.path.join(xroot, x))

  f = open(indexfile, "wb")
  try:
    i.dump(f)
  finally:
    f.close()

if __name__ == "__main__":
  if len(sys.argv) < 3:
    print "usage: %s [index file] [base path]" % sys.argv[0]
  else:
    main(sys.argv[1], sys.argv[2])
